<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    // NOTE that because we deployed Laravel with Sanctum, this User model class has had HasApiTokens trait defined with Sanctum superclass is deployed for every one of our instances of a user (as intermediated by this user model class)
    //This trait outputs a ApiToken i.e. session token that is granted upon registration and renewed/destroyed upon login or logout. So we attached each constructed user instance that is being fed into our database with this inherited trait that is generated by the user model class.
    // note that he first deploys this trait in relation to the /regisdter route within the scope of the AuthController controller class that is that route's arg2
    
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
